openapi: 3.0.1
info:
  title: Demo api
  description: Demo API
  version: v0.1
servers:
  - url: http://localhost:8080
    description: local dev environment
paths:
  /demo/jpa/create:
    post:
      summary: APi for olympics
      operationId: olympics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Olympics'
      responses:
        201:
          $ref: 'common-model.yml#/components/responses/201-Created'
        401:
          $ref: 'common-model.yml#/components/responses/401-Unauthorized'
        403:
          $ref: 'common-model.yml#/components/responses/403-Forbidden'
        404:
          $ref: 'common-model.yml#/components/responses/404-NotFound'
components:
  schemas:
    Olympics:
      title: Olympics
      type: object
      properties:
        id:
          type: string
          format: uuid
        sport:
          type: string
        venue:
          type: string
        participants:
          type: array
          items:
            $ref: '#/components/schemas/Participant'
    Participant:
      title: Participant
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        age:
          type: integer
        sex:
          type: string