spring:
  application:
    name: jooq-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/jooq-demo-db?reWriteBatchedInserts=true&currentSchema=public
    username: jooq-demo-user
    password: jooq
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
      generate_statistics: false
      show_sql: false
      jdbc:
        time_zone: UTC
        batch_size: 50
        batch_versioned_data: true
      order_inserts: true
      order_updates: true
      jdbc.lob.non_contextual_creation: true
      default_schema: public
      format_sql: true
    open-in-view: false
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml


springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui.html